{{- if .Values.nodePool.enabled }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.name }}
spec:
  template:
    metadata:
      labels:
        NodePool: {{ .Values.name }}
        NodeGroupType: {{ .Values.name }}
        {{- with .Values.nodePool.labels }}
        {{- range . }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
    spec:
      nodeClassRef:
        name: {{ .Values.name }}
        group: karpenter.k8s.aws
        kind: EC2NodeClass
      {{- with .Values.nodePool.taints }}
      taints:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodePool.requirements }}
      requirements:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      expireAfter: {{ .Values.nodePool.expireAfter }}
      terminationGracePeriod: {{ .Values.nodePool.terminationGracePeriod }}
  disruption:
    consolidationPolicy: {{ .Values.nodePool.disruption.consolidationPolicy }}
    {{- if eq .Values.nodePool.disruption.consolidationPolicy "WhenEmpty" }}
    consolidateAfter: {{ .Values.nodePool.disruption.consolidateAfter }} # Only defined if consolidationPolicy is WhenEmpty
    {{- end }}
    {{- with .Values.nodePool.disruption.budgets }}
    budgets:
    {{- toYaml . | nindent 4 }}
    {{- end }}    
  limits:
    cpu: {{ .Values.nodePool.limits.cpu }}
    memory: {{ .Values.nodePool.limits.memory }}
  weight: {{ .Values.nodePool.weight }}
{{- end }}
